import type { Metadata } from 'next';
import './globals.css';
import Header from '../components/layouts/header';
import Footer from '../components/layouts/footer';
import StoreProvider from './StoreProvider';
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className='font-outfit max-w-full flex flex-col'>
        <StoreProvider>
          <div className='max-w-full'>
            <Header />
          </div>
          <div className='flex flex-1'>{children}</div>
          <div className='max-w-full mt-auto'>
            <Footer />
          </div>
        </StoreProvider>
      </body>
    </html>
  );
}
