import type { Metadata } from 'next';
import './globals.css';
import Header from '../components/layouts/header';
import Footer from '../components/layouts/footer';
import StoreProvider from './StoreProvider';
import { Analytics } from '@vercel/analytics/next';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className='font-outfit min-h-screen flex flex-col max-w-screen'>
        <StoreProvider>
          <div className='flex mb-auto'>
            <Header />
          </div>

          <div className='flex-1 bg-white'>{children}</div>
          <Analytics />

          <div className='mt-auto'>
            <Footer />
          </div>
        </StoreProvider>
      </body>
    </html>
  );
}
